### ISSUE TITLE
License is `private`

### ISSUE THREAD

**Issue by cscleison** [antoinechalifour/remix-hexagonal-architecture#4]
Hi folks, I've created a simple todo app based a lot on the styles + components of this repo (thank you btw!), with the intention to create a small "incomplete" app that I can share with candidates when interviewing. However I just ran across the your license here and I've realized I don't have your _blessing_ for doing so... Would you mind - if this is what you want - changing it to something like MIT, just to for us to have a bit of peace of mind? 😄 
thanks!

**Comment by antoinechalifour** [comment]
Oh sure feel free to use the code :D I'll add an MIT license later this week ! Thanks for the feedback

Quick question : how did you find this project ? For some reason a few people end up leaving a star or forking but I have no idea how they found this repo 😂

**Comment by cscleison** [comment]
thank you so much!
I think I found it by the `todo` tag [here](https://reactjsexample.com/tag/todo/) and scrolled until I found a great looking one hehe

**Comment by antoinechalifour** [comment]
Done :)
